#@server=https://question-be.onrender.com
@server=http://localhost:4001

GET {{ server }}

### Auth Login
POST {{server}}/api/auth
Content-Type: application/json

{
    "email": "newuser@hotmail.com",
    "password": "123456"
}

### Auth Register
POST http://localhost:4001/api/auth/new
Content-Type: application/json

{
    "name": "anotheruser",
    "email": "anotheruser@hotmail.com",
    "password": "123456"
}

### Auth renew token
GET http://localhost:4001/api/auth/renew
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NzI5MTcwMWYzYmVmMmExMmE0NmQzNzEiLCJuYW1lIjoibmV3dXNlciIsImlhdCI6MTczMjAzNzIwNiwiZXhwIjoxNzMyMDQ0NDA2fQ.Z11IwJs9nPjjmYRapZNeToOUfjG305fVItBPnD9rofE

{    
    "email": "newuser@hotmail.com",
    "password": "123456"
}

### LLM
### Validate

GET {{ server }}/api/llm/validate?param=1
Content-Type: application/json

### generateTest
GET {{ server }}/api/llm/generateTest?llm=gemini&topic=Terraform

### Free prompt to test LLM.
GET {{ server }}/api/llm/openPrompt?prompt=What is CST timezone?

### Skills Match
POST {{ server }}/api/llm/skillsMatch
Content-Type: application/json

{
    "resume": "Senior developer with lot of experience in Javascript and React.",
    "skills": [
        "Javascript","React","Angular"
    ]
}